fn main() {
    // Compile icons.
    relm4_icons_build::bundle_icons(
        "icon_names.rs",
        Some("org.ljyh.linn"),
        Some("/org/ljyh/linn"),
        Some("data/icons"),
        [
            "heart-outline-thick",
            "heart-filled",
            "chat-bubble-text",
            "compass2",
            "broken-playback",
            "dock-left",
            "down-small",
            "go-home",
            "image-alt",
            "left-large",
            "library-music",
            "library",
            "list-compact",
            "loupe",
            "minus-large",
            "music-artist",
            "music-note-outline",
            "music-queue",
            "pause-large",
            "play-large",
            "playlist-consecutive",
            "playlist-repeat",
            "playlist-repeat-song",
            "playlist-shuffle",
            "plus-large",
            "search-folder",
            "skip-backward-large",
            "skip-forward-large",
            "speaker-0",
            "speaker-1",
            "speaker-2",
            "speaker-3",
            "speaker-4",
            "stop",
            "tornado",
        ],
    );

    glib_build_tools::compile_resources(&["data/icons"], "data/icons.gresource.xml", "icons.gresources");
}
