name: Flatpak

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: org.ljyh.linn.json
          bundle: Linn.flatpak
          artifact-name: Linn-${{ github.sha }}.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
